bootdo:
  uploadPath: /var/uploaded_files/
  username: test
  password: 111111
logging:
  level:
    root: error
    com.bootdo: info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hw2?useUnicode=true&characterEncoding=utf8
    username: root
    password: uAiqwVwjJ8-i
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
      host: localhost
      port: 6379
      password:
      timeout: 10000
      jedis:
        pool:
          max-idle: 8
          min-idle: 10
          max-active: 100
          max-wait: -1